"""Description of changes

Revision ID: 79574b1c3a28
Revises: 6c3be8100e29
Create Date: 2025-04-23 14:18:39.680732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79574b1c3a28'
down_revision = '6c3be8100e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_per_unit', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('frequency', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('max_points_per_frequency', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('max_points_per_frequency')
        batch_op.drop_column('frequency')
        batch_op.drop_column('points_per_unit')

    op.drop_table('points_request')
    # ### end Alembic commands ###
