"""Add response fields to points_request

Revision ID: a02148921fc6
Revises: 79574b1c3a28
Create Date: 2025-04-23 17:22:21.650932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a02148921fc6'
down_revision = '79574b1c3a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('points_requests')
    op.drop_table('category')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('points_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('points_awarded_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['awarded_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('points_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('response_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('processed_by', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('request_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('points_request_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['processed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('points_request_category_id_fkey', 'category', ['category_id'], ['id'])
        batch_op.alter_column('request_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('processed_by')
        batch_op.drop_column('response_notes')
        batch_op.drop_column('response_date')

    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('points_awarded_by_fkey', 'users', ['awarded_by'], ['id'])
        batch_op.create_foreign_key('points_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('points_per_unit', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('max_points_per_frequency', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    op.create_table('points_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('request_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('response_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='points_requests_category_id_fkey'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name='points_requests_processed_by_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='points_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='points_requests_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'Employee'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_first_login', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('us_non_us', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('exit_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('otp_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('employee_id', name='users_employee_id_key')
    )
    # ### end Alembic commands ###
